version: "3"

vars:
  ENTRY: server.js
  DIST_DIR: dist

tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list

  install:
    desc: Install dependencies
    cmds:
      - bun install

  install:ci:
    desc: Install dependencies (CI / lockfile enforced)
    cmds:
      - bun install --frozen-lockfile

  run:
    desc: Run the server
    cmds:
      - bun {{.ENTRY}}

  run:env:
    desc: Run the server with local .env
    cmds:
      - bun --env-file .env {{.ENTRY}}

  dev:
    desc: Run the server (watch)
    cmds:
      - |
        # Kill existing server if running
        pkill -f "bun --watch server.js" || true
        pkill -f "bun server.js" || true
        # Wait a moment for ports to free up
        sleep 1
        # Start server in background
        bun --watch server.js &
        SERVER_PID=$!
        # Wait for server to start (check port 3003)
        echo "Starting server..."
        for i in {1..30}; do
          if curl -s http://localhost:3003 > /dev/null 2>&1; then
            echo "Server started successfully!"
            # Open browser
            if command -v open > /dev/null 2>&1; then
              open http://localhost:3003
            elif command -v xdg-open > /dev/null 2>&1; then
              xdg-open http://localhost:3003
            elif command -v start > /dev/null 2>&1; then
              start http://localhost:3003
            fi
            # Keep server running
            wait $SERVER_PID
            break
          fi
          sleep 0.5
        done
        if ! curl -s http://localhost:3003 > /dev/null 2>&1; then
          echo "Failed to start server"
          exit 1
        fi

  dev:env:
    desc: Run the server (watch) with local .env
    cmds:
      - bun --watch --env-file .env {{.ENTRY}}

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf "{{.DIST_DIR}}"

  build:
    desc: Build bundle into dist/
    deps: [clean]
    cmds:
      - bun build "{{.ENTRY}}" --target=bun --outdir "{{.DIST_DIR}}"

  test:
    desc: Run tests
    cmds:
      - bun test

  test:coverage:
    desc: Run tests with coverage report
    cmds:
      - bun test --coverage

  ci:
    desc: CI / pre-commit checks
    deps: [install:ci, test, build]
    cmds:
      - echo "CI checks passed"
